INSERT INTO DICTIONARY (ID, ENGLISH_WORD, POLISH_WORD)
VALUES(1, 'cat', 'kot');
INSERT INTO DICTIONARY (ID, ENGLISH_WORD, POLISH_WORD)
VALUES(2, 'dog', 'pies');
INSERT INTO DICTIONARY (ID, ENGLISH_WORD, POLISH_WORD)
VALUES(3, 'lion', 'lew');
INSERT INTO DICTIONARY (ID, ENGLISH_WORD, POLISH_WORD)
VALUES(4, 'umbrella', 'parasol');